name: scheduled workflow test

on:
  schedule:
    - cron:  '*/15 * * * *'
jobs:
  build:
    name: Hello world action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./action-a
        with:
          MY_NAME: "Heiker"

  